language: node_js
node_js:
  - 8

cache:
  directories:
    - node_modules

before_script:
    - echo "About to deploy"

script:
    - echo "Deploying !"
    - npm install
    - npm run build

install:
    - npm install -g firebase-tools

after_success:
    - firebase deploy --token $FIREBASE_TOKEN
    - echo "Successfully deployed"

branches:
  only:
  - master

notifications:
  email: false
